admin_chat_id: "-123456789" # Optional. Will send a report after every run.
bot_token: 123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11 # Your bot token, you should get this when you create your bot. You can either define it here or in environment variables.
feeds:
  - name: feed1 # Example: NYTimes HP
    url: url1 # Example: https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml
  - name: feed2
    url: url2
    interval: 120 # Optional. Default: 60 (minutes)
rssgroups: # You can group your feeds here
  - name: group1 # A group containing 2 feeds
    feeds:
      - feed1
      - feed2
chats:
  chat_id_1: group1 # Push the content from `group1` to the chat with `chan_id_1`
  chat_id_2: feed1 # Push `feed1` to `chat_id_2`
